// Code generated by protoc-gen-go. DO NOT EDIT.
// source: social.datacapture.proto

package social_datacapture

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_datacapture_74ececd98b414662, []int{0}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserResponse struct {
	NickName             string   `protobuf:"bytes,1,opt,name=NickName" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_datacapture_74ececd98b414662, []int{1}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "GetUserResponse")
}

func init() {
	proto.RegisterFile("social.datacapture.proto", fileDescriptor_social_datacapture_74ececd98b414662)
}

var fileDescriptor_social_datacapture_74ececd98b414662 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0xce, 0x4f, 0xce,
	0x4c, 0xcc, 0xd1, 0x4b, 0x49, 0x2c, 0x49, 0x4c, 0x4e, 0x2c, 0x28, 0x29, 0x2d, 0x4a, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe0, 0xe2, 0x73, 0x4f, 0x2d, 0x09, 0x2d, 0x4e, 0x2d, 0x0a,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x03, 0x71, 0x3d, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x25, 0x5d, 0x2e, 0x7e, 0xb8, 0xca, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x29, 0x2e, 0x0e, 0xbf, 0xcc, 0xe4, 0x6c, 0xbf, 0xc4, 0xdc, 0x54, 0xb0,
	0x62, 0xce, 0x20, 0x38, 0xdf, 0xc8, 0x96, 0x8b, 0x1b, 0xa4, 0x36, 0x38, 0xb5, 0xa8, 0x2c, 0x33,
	0x39, 0x55, 0x48, 0x8f, 0x8b, 0x1d, 0xaa, 0x5b, 0x88, 0x5f, 0x0f, 0xd5, 0x46, 0x29, 0x01, 0x3d,
	0x34, 0x83, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xce, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x70,
	0xe2, 0x28, 0x48, 0xba, 0x00, 0x00, 0x00,
}
